goals: {x: 1, y: 1}

gains: {lookahead: 2.0, look_forward: 5.0, propotional: 2.0, differential: 0.0, integral: 0.0}

look_ahead_constant: 2.0 # meters

base_width: 2.9 # meters

time_step: 0.1 # seconds
