SimplePurePursuitNODE:
  ros_parameters:
        look_ahead_constant: 4
        speed_target: 2.0
        rate: 10


        control:
          actions_topic: "cmd"
          waypoints_topic: "waypoints_clean"
          marker_viz_topic: "marker_viz"
          frame_id: "rear_link"
