Controller:
  ros__parameters:
    Navigation:
      adaptivePurePursuit:
        adaptivePurePursuit:

          time_step:
            default: 0.1
            description: Time step
            type: double


          speed:
            maximum:
              default: 6.0
              description: Maximum speed
              type: double
            minimum:
              default: 3.0
              description: Minimum speed
              type: double


          gains:
            proportional:
              default: 2.0
              description: Proportional gain
              type: double
            integral:
              default: 0.0
              description: Integral gain
              type: double
            differential:
              default: 0.0
              description: Differential gain
              type: double
            lookahead:
              default: 0.3
              description: Lookahead gain
              type: double


          constants:
            speed:
              default: 63.0
              description: Speed constant
              type: double
            lookahead:
              default: 1.1
              description: Lookahead constant
              type: double

        topics:
          drive:
            default: /drive
            description: Drive topic
            type: string
          state:
            default: /state
            description: State topic
            type: string
          path:
            default: /path
            description: Path topic
            type: string
