
gains: {lookahead: 2.0, look_forward: 0.3, propotional: 0.5, differential: 0.4, integral: 0.5}

look_ahead_constant: 2.0 # meters

base_length: 2.9 # meters

time_step: 0.1 # seconds

speed: {max: 20.0, min: 2.0, target: 10.0} # m/s

acceleration: {max: 15.0, min: -15.0} # m/s^2
