yoloNode:
  ros__parameters:
    perception:
      yolo:
        frame_id: "kit"
        camera_feed: "/perception/camera_interface/camera_feed"
        detections: "/perception/yolo/detections"
        cropped_detections: "/perception/yolo/cropped_detections"

    model:
      model_path: "/home/mazen/fs_ws/src/fs-system/perception/yolo/yolo/models/best.pt"